name: Common environment setup

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt-get install -y llvm clang dwz cmake curl unzip
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go}}
        check-latest: true
        cache-dependency-path: go.sum
      id: go
