dist:
  name: profiling-collector
  description: Profiling OTel Collector distribution
  output_path: ./collector
  otelcol_version: 0.104.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.104.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.104.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.104.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.104.0
  - gomod:
      github.com/elastic/otel-profiling-agent v0.0.0-20240726092723-37a757cac3a2
    import: github.com/elastic/otel-profiling-agent/otel/receiver
    name: profilingreceiver
